# Generated by Django 6.1 on 2026-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
